version: '3.8'

services:
  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/carbon_tracker?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Shashi@123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
    depends_on:
      - mysql-db
    networks:
      - carbon-network
    restart: unless-stopped

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Shashi@123
      MYSQL_DATABASE: carbon_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - carbon-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  carbon-network:
    driver: bridge

